version: "3.8"

services:
  backend:
    image: ${{ secrets.NCP_CONTAINER_REGISTRY }}/server-spring:${{ needs.build.outputs.sha }}
    container_name: server-spring
    restart: always
    network_mode: host
