spring:
  config:
    activate:
      on-profile: "datasource"
  datasource:
    url: jdbc:oracle:thin:@${DB_CONNECTION_STRING}
    hikari:
      maxLifetime: 580000
      maximum-pool-size: 20
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: ${JPA_BATCH_FETCH_SIZE:100}
