spring:
  config:
    activate:
      on-profile: "storage"
storage:
  accessKey: ${STORAGE_ACCESS_KEY:}
  secretKey: ${STORAGE_SECRET_KEY:}
  bucket: ${STORAGE_BUCKET:}
  region: ${STORAGE_REGION:}
  endpoint: ${STORAGE_ENDPOINT:https://kr.object.ncloudstorage.com}
