jwt:
  access-token-secret: ${JWT_ACCESS_TOKEN_SECRET:}
  refresh-token-secret: ${JWT_REFRESH_TOKEN_SECRET:}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME:7200}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME:604800}
  issuer: ${JWT_ISSUER:}

oidc:
  nonce: ${OIDC_NONCE_SECRET:}
  kakao:
    jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
    issuer: https://kauth.kakao.com
    audience:
      - ${KAKAO_REST_APP_KEY:}
      - ${KAKAO_NATIVE_APP_KEY:}
  apple:
    jwk-set-uri: https://appleid.apple.com/auth/keys
    issuer: https://appleid.apple.com
    audience:
      - ${APPLE_SERVICE_ID:}

oauth:
  nonce: ${OIDC_NONCE_SECRET:}
  audience:
    KAKAO:
      - key: ${KAKAO_REST_APP_KEY:}
        type: WEB
      - key: ${KAKAO_NATIVE_APP_KEY:}
        type: APP
    APPLE:
      - key: ${APPLE_SERVICE_ID:}
        type: ALL
