#!/bin/bash
echo "Running spotless check"
./gradlew spotlessCheck
if [ \$? -eq 0 ]
then
    echo "Spotless check succeed"
else
    echo "Spotless check failed" >&2
    ./gradlew spotlessApply

    # Add files to stage spotless applied
    for file in $targetFiles; do
      if test -f "$file"; then
        git add $file
      fi
    done
exit 1
fi
