name: develop Deploy

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'commit_hash'
        required: true

env:
  DOCKERHUB_USERNAME: tenminutes

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      # EC2로 배포
      - name: Deploy to EC2 Server
        uses: appleboy/ssh-action@master
        env:
          IMAGE_FULL_URL: ${{ steps.metadata.outputs.tags }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: IMAGE_FULL_URL # docker-compose.yml 에서 사용할 환경 변수
          script: |
            echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin
            docker pull ${{ env.IMAGE_FULL_URL }}
            docker compose up -d
            docker exec -d nginx nginx -s reload
            docker image prune -a -f
